from enum import Enum

class NumEscolhas(Enum):
    VESTUARIO= 1
    ATIVIDADES_EXTERNAS = 2
    PREVISAO_CHUVA = 3
    AVALIACAO_DE_CONFORTO = 4
    EFICIENCIA_ENERGETICA = 5
    SEGURANCA_VIARIA = 6
    ATIVIDADES_AGRICOLAS = 7